name: CI
permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      # Provide dummy keys so imports that read env vars don't crash in CI
      OPENROUTER_API_KEY: DUMMY
      SERPAPI_KEY: DUMMY
      WP_URL: http://localhost
      WP_USER: user
      WP_APP_PASS: pass
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies (runtime + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Run tests
        run: pytest

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
