name: WordPress Connectivity Check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-wp:
    name: Check WordPress connectivity
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WordPress connectivity check
        run: python scripts/wp_check.py
